#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pytest_mock
Version  : 3.6.1
Release  : 6
URL      : https://files.pythonhosted.org/packages/b3/08/b131e1b5c628a7d46c9b8d676a86a8d235bced79b9d90845500e39df81b9/pytest-mock-3.6.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/b3/08/b131e1b5c628a7d46c9b8d676a86a8d235bced79b9d90845500e39df81b9/pytest-mock-3.6.1.tar.gz
Summary  : Thin-wrapper around the mock package for easier use with pytest
Group    : Development/Tools
License  : MIT
Requires: pypi-pytest_mock-license = %{version}-%{release}
Requires: pypi-pytest_mock-python = %{version}-%{release}
Requires: pypi-pytest_mock-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
Provides: pytest-mock
Provides: pytest-mock-python
Provides: pytest-mock-python3
BuildRequires : pypi(pluggy)
BuildRequires : py-python
BuildRequires : pypi(pytest)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pytest
BuildRequires : tox
BuildRequires : pypi(virtualenv)

%description
pytest-mock
        ===========
        
        This plugin provides a ``mocker`` fixture which is a thin-wrapper around the patching API

%package license
Summary: license components for the pypi-pytest_mock package.
Group: Default

%description license
license components for the pypi-pytest_mock package.


%package python
Summary: python components for the pypi-pytest_mock package.
Group: Default
Requires: pypi-pytest_mock-python3 = %{version}-%{release}

%description python
python components for the pypi-pytest_mock package.


%package python3
Summary: python3 components for the pypi-pytest_mock package.
Group: Default
Requires: python3-core
Provides: pypi(pytest_mock)
Requires: pypi(pytest)

%description python3
python3 components for the pypi-pytest_mock package.


%prep
%setup -q -n pytest-mock-3.6.1
cd %{_builddir}/pytest-mock-3.6.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641480829
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pytest_mock
cp %{_builddir}/pytest-mock-3.6.1/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pytest_mock/6ca8a49e647337bafa8bf4d5ecf611f59069ce31
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pytest_mock/6ca8a49e647337bafa8bf4d5ecf611f59069ce31

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
