#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pytest_mock
Version  : 3.7.0
Release  : 8
URL      : https://files.pythonhosted.org/packages/96/e1/fb53b62056e6840a36d9a4beb4e42726155594c567b574103435a7131c60/pytest-mock-3.7.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/96/e1/fb53b62056e6840a36d9a4beb4e42726155594c567b574103435a7131c60/pytest-mock-3.7.0.tar.gz
Summary  : Thin-wrapper around the mock package for easier use with pytest
Group    : Development/Tools
License  : MIT
Requires: pypi-pytest_mock-license = %{version}-%{release}
Requires: pypi-pytest_mock-python = %{version}-%{release}
Requires: pypi-pytest_mock-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(py)
BuildRequires : pypi(pytest)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
===========
pytest-mock
===========
This plugin provides a ``mocker`` fixture which is a thin-wrapper around the patching API
provided by the `mock package <http://pypi.python.org/pypi/mock>`_:

%package license
Summary: license components for the pypi-pytest_mock package.
Group: Default

%description license
license components for the pypi-pytest_mock package.


%package python
Summary: python components for the pypi-pytest_mock package.
Group: Default
Requires: pypi-pytest_mock-python3 = %{version}-%{release}

%description python
python components for the pypi-pytest_mock package.


%package python3
Summary: python3 components for the pypi-pytest_mock package.
Group: Default
Requires: python3-core
Provides: pypi(pytest_mock)
Requires: pypi(pytest)

%description python3
python3 components for the pypi-pytest_mock package.


%prep
%setup -q -n pytest-mock-3.7.0
cd %{_builddir}/pytest-mock-3.7.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1643389771
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pytest_mock
cp %{_builddir}/pytest-mock-3.7.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pytest_mock/6ca8a49e647337bafa8bf4d5ecf611f59069ce31
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pytest_mock/6ca8a49e647337bafa8bf4d5ecf611f59069ce31

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
